kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/molnars/prom_exporter.git'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"prom-exporter:latest","namespace":"inotify"},"fieldPath":"spec.template.spec.containers[?(@.name==\"prom-exporter\")].image","pause":"false"}]
  name: prom-exporter
  namespace: inotify
  labels:
    app: prom-exporter
    app.kubernetes.io/component: prom-exporter
    app.kubernetes.io/instance: prom-exporter
    app.kubernetes.io/name: prom-exporter
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi9
spec:
  selector:
    matchLabels:
      app: prom-exporter
  template:
    metadata:
      labels:
        app: prom-exporter
        deployment: prom-exporter
    spec:
      restartPolicy: Always
      hostPID: true
      schedulerName: default-scheduler
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            requests:
              cpu: 8m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          name: prom-exporter
          env:
            - name: APP_FILE
              value: prom_exporter.py
            - name: frequency
              value: '60'
            - name: DEBUG
              value: 'false'
          securityContext:
            privileged: true
            runAsUser: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: true
          ports:
            - hostPort: 9000
              containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: proc
              readOnly: true
              mountPath: /host/proc
              mountPropagation: HostToContainer
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/inotify/prom-exporter@sha256:78e2508c1aae8a0cfe94c91f5ab59a17e571fc9437ad7747f15dd02deaf82727
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: ''
      dnsPolicy: ClusterFirst

