kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/molnars/prom_exporter.git'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"prom-exporter:latest","namespace":"inotify"},"fieldPath":"spec.template.spec.containers[?(@.name==\"prom-exporter\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  name: prom-exporter
  namespace: inotify
  labels:
    app: prom-exporter
    app.kubernetes.io/component: prom-exporter
    app.kubernetes.io/instance: prom-exporter
    app.kubernetes.io/name: prom-exporter
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
spec:
  selector:
    matchLabels:
      app: prom-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prom-exporter
        deployment: prom-exporter
    spec:
      volumes:
        - name: sys
          hostPath:
            path: /sys
            type: ''
        - name: root
          hostPath:
            path: /
            type: ''
      containers:
        - resources:
            requests:
              cpu: 8m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          name: prom-exporter
          env:
            - name: APP_FILE
              value: prom_exporter.py
            - name: frequency
              value: '60'
          securityContext:
            privileged: true
            runAsUser: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/inotify/prom-exporter@sha256:fc927ab392ac8960e1e36171ef1765edbdf7a84dff16ff29f942aecfdae21c43
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      hostPID: true
      securityContext: {}
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10

