apiVersion: v1
kind: Service
metadata:
  name: prom-exporter-service
  labels:
    app: prom-exporter
spec:
  selector:
    app: prom-exporter
  ports:
    - name: metrics
      port: 9000
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prom-exporter
  name: prom-exporter-monitor
spec:
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - inotify
  selector:
    matchLabels:
      app: prom-exporter
